pipeline:
  name: petclinic-ci
  identifier: petclinicci
  projectIdentifier: default_project
  orgIdentifier: default
  properties:
    ci:
      codebase:
        connectorRef: git_petclinic
        repoName: harness-spring-petclinic
        build: <+input>
  stages:
    - stage:
        name: BuildAndTest
        identifier: Build_and_Test
        template:
          templateRef: Maven_Build_and_Push
          versionLabel: "1.0"
          templateInputs:
            type: CI
            spec:
              execution:
                steps:
                  - step:
                      identifier: Build_and_Push_Image
                      type: BuildAndPushDockerRegistry
                      spec:
                        repo: pgasp/harness-spring-petclinic
    - stage:
        name: Security Scan
        identifier: Security_Scan
        type: SecurityTests
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: k8slocal
              namespace: harness-build
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: AquaTrivy
                  name: Trivy Image Scan
                  identifier: Trivy_Image_Scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: container
                      name: harness-spring-petclinic
                      variant: <+pipeline.sequenceId>
                    advanced:
                      log:
                        level: info
                      fail_on_severity: none
                    privileged: true
                    image:
                      type: docker_v2
                      tag: <+pipeline.sequenceId>
                      access_id: pgasp
                      access_token: <+secrets.getValue("docker_hub")>
                      name: pgasp/harness-spring-petclinic
                      domain: docker.io
                    resources:
                      limits:
                        memory: 2Gi
                      requests:
                        memory: 1Gi
    - stage:
        name: Deploy DEV
        identifier: deployment
        template:
          templateRef: K8s_Canary_Rolling_Deploy
          versionLabel: "1.0"
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              environment:
                environmentRef: dev_petclinic
                infrastructureDefinitions:
                  - identifier: dev
    - stage:
        name: Deploy UAT
        identifier: Deploy_UAT
        template:
          templateRef: K8s_Canary_Rolling_Deploy
          versionLabel: "1.0"
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              environment:
                environmentRef: dev_petclinic
                infrastructureDefinitions:
                  - identifier: uat
    - stage:
        name: Approval PROD
        identifier: Approval_PROD
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approve Production Deployment
                  identifier: Approve_Production_Deployment
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Veuillez valider les résultats du déploiement UAT avant de promouvoir en production.
                      Pipeline: <+pipeline.name>
                      Build: <+pipeline.sequenceId>
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - _project_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
        failureStrategies: []
    - stage:
        name: Deploy PROD
        identifier: Deploy_PROD
        template:
          templateRef: K8s_Canary_Rolling_Deploy
          versionLabel: "1.0"
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: <+input>
                          sources: <+input>
              environment:
                environmentRef: dev_petclinic
                infrastructureDefinitions:
                  - identifier: prod
